import type { Metadata } from "next";
import { WaitlistForm } from "../_components/public-form";

export const metadata: Metadata = { title: "Join the Waitlist", description: "Join the Nexvia pilot waitlist for personalized career roadmaps, readiness tools, mentorship, and career-relevant opportunities.", alternates: { canonical: "/waitlist" } };

export default function WaitlistPage() {
  const benefits = [["Students", "Get an early personalized AI roadmap."], ["Colleges", "See cohort skill gaps and readiness signals."], ["Recruiters", "Discover talent through relevant evidence."], ["Parents", "Understand learning direction and progress."]] as const;
  return <main className="mx-auto grid w-full max-w-6xl gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">Founding pilot cohort</p><h1 className="mt-4 font-display text-4xl uppercase text-white sm:text-6xl">Be first to test the complete career loop.</h1><p className="mt-6 text-lg leading-8 text-slate-400">Join the first 50 pilot testers helping us validate explainable roadmaps, readiness signals, and career-aligned opportunity matching.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{benefits.map(([audience, benefit]) => <article key={audience} className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><h2 className="font-bold text-white">For {audience.toLowerCase()}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{benefit}</p></article>)}</div><p className="mt-6 text-sm text-cyan-200">Early access · direct feedback channel · no payment required</p></div><section className="rounded-3xl border border-violet-300/20 bg-white/[.04] p-6 sm:p-8"><h2 className="text-2xl font-bold text-white">Reserve your place</h2><p className="mt-2 text-sm text-slate-400">Tell us which workspace matters to you. You can opt out at any time.</p><div className="mt-6"><WaitlistForm /></div></section></main>;
}
