import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { BarChart3, BookOpenCheck, Target, UsersRound } from "lucide-react";
import { addCohortMember, createCohort, createTrainingAssignment } from "./actions";

export const dynamic = "force-dynamic";

export default async function UpskillingPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");
  const { data: membership } = await supabase.from("company_members").select("company_id,companies(name)").eq("user_id", user.id).limit(1).maybeSingle();
  if (!membership) redirect("/recruiter/setup");
  const { data: cohorts } = await supabase.from("employer_cohorts").select("*, employer_cohort_members(*), training_assignments(*)").eq("company_id", membership.company_id).order("created_at", { ascending: false });
  const allMembers = (cohorts ?? []).flatMap((cohort) => cohort.employer_cohort_members ?? []);
  const averageReadiness = allMembers.length ? Math.round(allMembers.reduce((sum, member) => sum + member.readiness_score, 0) / allMembers.length) : 0;
  const missing = new Map<string, number>();
  allMembers.forEach((member) => {
    const current = new Set((member.current_skills as string[]).map((skill) => skill.toLowerCase()));
    (member.target_skills as string[]).filter((skill) => !current.has(skill.toLowerCase())).forEach((skill) => missing.set(skill, (missing.get(skill) ?? 0) + 1));
  });
  const gaps = [...missing.entries()].sort((a, b) => b[1] - a[1]).slice(0, 8);

  return <main className="mx-auto w-full max-w-7xl px-4 py-10 sm:px-6"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-500">Employer learning workspace</p><h1 className="mt-2 text-3xl font-bold text-foreground">Employee Upskilling</h1><p className="mt-2 text-sm text-slate-400">Build cohorts, expose skill gaps, and assign training with accountable progress.</p></header>
    <section className="mt-8 grid gap-4 sm:grid-cols-3"><Metric icon={UsersRound} label="Employees" value={allMembers.length} /><Metric icon={BarChart3} label="Average readiness" value={`${averageReadiness}%`} /><Metric icon={Target} label="Open skill gaps" value={gaps.reduce((sum, gap) => sum + gap[1], 0)} /></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-3"><form action={createCohort} className="rounded-2xl border border-line bg-card p-6"><h2 className="font-bold text-foreground">Create cohort</h2><div className="mt-4 grid gap-3"><input name="name" required placeholder="Graduate engineering cohort" className="rounded-xl border border-line bg-background px-3 py-2.5 text-sm" /><input name="target_role" placeholder="Target role" className="rounded-xl border border-line bg-background px-3 py-2.5 text-sm" /><textarea name="description" placeholder="Cohort objective" className="rounded-xl border border-line bg-background px-3 py-2.5 text-sm" /><div className="grid grid-cols-2 gap-2"><input name="starts_on" type="date" className="rounded-xl border border-line bg-background px-3 py-2.5 text-sm" /><input name="ends_on" type="date" className="rounded-xl border border-line bg-background px-3 py-2.5 text-sm" /></div><button className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white">Create cohort</button></div></form>
      <form action={addCohortMember} className="rounded-2xl border border-line bg-card p-6"><h2 className="font-bold text-foreground">Add employee</h2><div className="mt-4 grid gap-3"><CohortSelect cohorts={cohorts ?? []} /><input name="employee_name" required placeholder="Employee name" className="rounded-xl border border-line bg-background px-3 py-2.5 text-sm" /><input name="employee_email" required type="email" placeholder="Work email" className="rounded-xl border border-line bg-background px-3 py-2.5 text-sm" /><input name="current_skills" placeholder="Current skills, comma separated" className="rounded-xl border border-line bg-background px-3 py-2.5 text-sm" /><input name="target_skills" placeholder="Target skills, comma separated" className="rounded-xl border border-line bg-background px-3 py-2.5 text-sm" /><input name="readiness_score" type="number" min="0" max="100" placeholder="Readiness score" className="rounded-xl border border-line bg-background px-3 py-2.5 text-sm" /><button className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white">Add employee</button></div></form>
      <form action={createTrainingAssignment} className="rounded-2xl border border-line bg-card p-6"><h2 className="font-bold text-foreground">Assign training</h2><div className="mt-4 grid gap-3"><CohortSelect cohorts={cohorts ?? []} /><input name="title" required placeholder="Training title" className="rounded-xl border border-line bg-background px-3 py-2.5 text-sm" /><input name="skill_name" required placeholder="Skill developed" className="rounded-xl border border-line bg-background px-3 py-2.5 text-sm" /><input name="resource_url" type="url" placeholder="Learning resource URL" className="rounded-xl border border-line bg-background px-3 py-2.5 text-sm" /><input name="due_at" type="datetime-local" className="rounded-xl border border-line bg-background px-3 py-2.5 text-sm" /><button className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white">Assign to cohort</button></div></form></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-[1fr_2fr]"><div className="rounded-2xl border border-line bg-card p-6"><h2 className="font-bold text-foreground">Top skill gaps</h2><div className="mt-5 grid gap-3">{gaps.map(([skill, count]) => <div key={skill}><div className="flex justify-between text-sm"><span className="text-foreground">{skill}</span><span className="text-slate-400">{count} employees</span></div><div className="mt-2 h-2 rounded-full bg-blue-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.min(100, count / Math.max(1, allMembers.length) * 100)}%` }} /></div></div>)}{gaps.length === 0 && <p className="text-sm text-slate-400">Add employees and target skills to generate a report.</p>}</div></div><div className="grid gap-4">{(cohorts ?? []).map((cohort) => <article key={cohort.id} className="rounded-2xl border border-line bg-card p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-500">{cohort.status}</p><h2 className="mt-1 text-lg font-bold text-foreground">{cohort.name}</h2><p className="mt-1 text-sm text-slate-400">{cohort.target_role || "Open development track"}</p></div><div className="flex gap-2"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{cohort.employer_cohort_members?.length ?? 0} people</span><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{cohort.training_assignments?.length ?? 0} trainings</span></div></div></article>)}{(cohorts ?? []).length === 0 && <div className="rounded-2xl border border-dashed border-line p-10 text-center"><BookOpenCheck className="mx-auto h-8 w-8 text-blue-500" /><p className="mt-3 text-sm text-slate-400">Create the first employee cohort to begin.</p></div>}</div></section>
  </main>;
}

function CohortSelect({ cohorts }: { cohorts: Array<{ id: string; name: string }> }) { return <select name="cohort_id" required className="rounded-xl border border-line bg-background px-3 py-2.5 text-sm"><option value="">Choose cohort</option>{cohorts.map((cohort) => <option key={cohort.id} value={cohort.id}>{cohort.name}</option>)}</select>; }
function Metric({ icon: Icon, label, value }: { icon: typeof UsersRound; label: string; value: string | number }) { return <div className="rounded-2xl border border-blue-200 bg-blue-50 p-5 dark:border-blue-400/20 dark:bg-blue-500/10"><Icon className="h-5 w-5 text-blue-600" /><p className="mt-4 text-3xl font-bold text-foreground">{value}</p><p className="mt-1 text-xs font-bold uppercase tracking-widest text-slate-400">{label}</p></div>; }
