import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpenCheck, BriefcaseBusiness, Building2, Compass, ShieldCheck, Target } from "lucide-react";
import { PublicNav } from "./_components/public-nav";
import { DemoJourneyAnimation } from "./demo/demo-journey";

export const metadata: Metadata = {
  title: "Nexvia — Discover your direction. Build your future.",
  description: "Nexvia helps students find suitable careers, build the right skills, and prepare for real opportunities.",
  alternates: { canonical: "/" },
};

const benefits = [
  { icon: Compass, title: "Find a direction that fits", text: "Explore career matches with clear reasons based on your interests, strengths, and goals." },
  { icon: BookOpenCheck, title: "Know what to learn next", text: "Turn missing skills into a manageable learning plan with practical projects and milestones." },
  { icon: Target, title: "Prepare with confidence", text: "Practise interviews, improve your resume, and build evidence of what you can do." },
];
const faqs = [
  ["Can I explore Nexvia without an account?", "Yes. The student demo walks through a sample profile, assessment, career match, roadmap, practice, and opportunity. Explore every step without signing in."],
  ["How are career recommendations explained?", "Nexvia compares your assessment, interests, skills, and career goals. It shows the reasons behind each match so you can compare directions and make your own choice. A match is guidance, not a guarantee of employment."],
  ["What happens after I choose a career?", "You receive a learning roadmap. Complete activities in order, build projects, practise interviews, and prepare for opportunities relevant to your chosen direction."],
  ["Who can see my information?", "Access depends on your workspace and role. Portfolio evidence starts as self-reported; verification requires an authorized reviewer. Optional analytics require your consent."],
  ["Can my institution or employer use Nexvia?", "Yes. Institutions can follow learner readiness and collaborate with employers. Employers can publish opportunities and review candidate evidence. Contact us to discuss a pilot."],
];

export default function Home() {
  return <div className="premium-page"><PublicNav /><div>
    <section className="premium-section grid items-center gap-12 py-20 lg:grid-cols-[1.15fr_.85fr] lg:py-28">
      <div><p className="premium-eyebrow">Your career, with a clearer plan</p><h1 className="mt-5 max-w-3xl text-[2.75rem] font-bold leading-[1.1] tracking-[-.045em] sm:text-5xl xl:text-[4rem]">Discover your direction. <span className="text-accent">Build your future.</span></h1><p className="premium-muted mt-6 max-w-xl text-lg leading-8">Nexvia helps students find suitable careers, build the right skills, and prepare for real opportunities.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/demo" className="premium-button">Explore student demo <ArrowRight className="h-4 w-4" /></Link><Link href="/signup/student" className="premium-button-secondary">Create free account</Link></div><p className="premium-muted mt-5 text-sm">Explore the demo without signing in.</p></div>
      <div className="premium-card p-6 sm:p-8" aria-label="Sample student dashboard preview"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-line pb-5"><span className="font-semibold">Your career workspace</span><span className="premium-muted text-xs">Sample preview</span></div><div className="mt-6 rounded-xl bg-accent-soft p-5"><p className="premium-eyebrow">Your next step</p><h2 className="mt-3 text-xl font-semibold">Build your first frontend project</h2><p className="premium-muted mt-2 text-sm leading-6">Put your JavaScript skills into practice with a responsive portfolio.</p><Link href="/demo" className="mt-4 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-accent">View the learning plan <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-6 flex items-center justify-between gap-3 text-sm"><span className="premium-muted">Roadmap progress</span><span className="font-semibold">3 of 8 milestones</span></div><div className="mt-3 h-2 rounded-full bg-accent-soft"><div className="h-full w-[37.5%] rounded-full bg-accent" /></div><p className="premium-muted mt-5 flex items-center gap-2 text-xs"><ShieldCheck className="h-4 w-4 text-accent" /> Clear reasons. Practical next steps. Your choice.</p></div>
    </section>
    <section id="how-it-works" className="premium-section py-16"><p className="premium-eyebrow">How it works</p><h2 className="premium-heading mt-3">A clear path in three steps</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{[["01", "Discover your strengths", "Share your goals and complete an assessment to understand what suits you."], ["02", "Build the right skills", "Choose your direction and follow a learning plan with practical milestones."], ["03", "Prepare for opportunities", "Practise, collect evidence, and explore roles that fit your growing skills."]].map(([number, title, text]) => <article key={number} className="premium-card p-6 sm:p-8"><span className="premium-icon text-sm font-bold">{number}</span><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="premium-muted mt-3 text-sm leading-7">{text}</p></article>)}</div></section>
    <section id="product" className="premium-section py-16"><p className="premium-eyebrow">Interactive product preview</p><h2 className="premium-heading mt-3">See how your next step becomes clearer</h2><p className="premium-muted mt-4 max-w-2xl leading-7">Follow Aarav, a sample student exploring frontend development. Select a step to see the understanding, recommendation, and action behind it.</p><DemoJourneyAnimation /></section>
    <section id="students" className="premium-section py-16"><p className="premium-eyebrow">For students</p><h2 className="premium-heading mt-3">Less uncertainty. More useful progress.</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{benefits.map(({ icon: Icon, title, text }) => <article key={title} className="premium-card p-6 sm:p-8"><span className="premium-icon"><Icon className="h-5 w-5" /></span><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="premium-muted mt-3 text-sm leading-7">{text}</p></article>)}</div></section>
    <section className="premium-section py-16"><p className="premium-eyebrow">Institutions and employers</p><h2 className="premium-heading mt-3">Connect learning to opportunity</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{[{ id: "colleges", icon: Building2, title: "Support your students’ next steps", text: "Follow cohort readiness, understand skill gaps, and connect students with employer opportunities.", href: "/signup/academia", action: "Explore institution workspace" }, { id: "recruiters", icon: BriefcaseBusiness, title: "Find talent through practical evidence", text: "Publish opportunities, review relevant candidates, and collaborate with institutions on the skills you need.", href: "/signup/industry", action: "Explore employer workspace" }].map(({ id, icon: Icon, title, text, href, action }) => <article id={id} key={id} className="premium-card scroll-mt-24 p-6 sm:p-8"><span className="premium-icon"><Icon className="h-5 w-5" /></span><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="premium-muted mt-3 leading-7">{text}</p><Link href={href} className="mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-accent">{action} <ArrowRight className="h-4 w-4" /></Link></article>)}</div></section>
    <section className="premium-section py-16" aria-labelledby="student-story"><div className="premium-card grid gap-8 p-6 sm:p-8 lg:grid-cols-[1.2fr_.8fr]"><div><p className="premium-eyebrow">Sample student story · illustrative, not a testimonial</p><h2 id="student-story" className="premium-heading mt-4">From a broad goal to a practical plan</h2><p className="premium-muted mt-5 text-lg leading-8">Aarav wants to become a frontend developer but is unsure what to learn next. The demo shows how his interests and current skills become an 11-week plan covering foundations, a React project, and interview preparation.</p><Link href="/demo" className="mt-5 inline-flex min-h-11 items-center gap-2 font-semibold text-accent">Explore Aarav’s sample journey <ArrowRight className="h-4 w-4" /></Link></div><div className="rounded-xl bg-accent-soft p-6"><ShieldCheck className="h-6 w-6 text-accent" /><h3 className="mt-4 font-semibold">Your progress, explained</h3><p className="premium-muted mt-3 text-sm leading-7">Recommendations show their reasons. Evidence is labelled as self-reported until reviewed. Career matches support your decisions and never promise an outcome.</p><p className="premium-muted mt-4 text-sm leading-7">Essential storage keeps your account working. Optional analytics are your choice.</p></div></div></section>
    <section className="premium-section py-16"><div className="premium-featured rounded-2xl p-8 text-center sm:p-12"><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Your future starts with one clear step</h2><p className="mt-4 leading-7">Discover what suits you and start building the skills to get there.</p><Link href="/signup/student" className="premium-button mt-7">Create free account <ArrowRight className="h-4 w-4" /></Link></div></section>
    <section id="faq" className="premium-section pb-24 pt-16"><p className="premium-eyebrow">Questions, answered</p><h2 className="premium-heading mt-3">Before you get started</h2><div className="mt-8 space-y-3">{faqs.map(([question, answer]) => <details key={question} className="premium-card group p-6"><summary className="flex min-h-6 cursor-pointer list-none items-center justify-between gap-5 font-semibold">{question}<span className="text-xl text-accent group-open:rotate-45" aria-hidden>+</span></summary><p className="premium-muted mt-4 max-w-3xl text-sm leading-7">{answer}</p></details>)}</div></section>
  </div></div>;
}
