import type { Metadata } from "next";
import Link from "next/link";
import { getApprovedReviews } from "@/lib/public-site";
import { createClient } from "@/lib/supabase/server";
import { ReviewForm } from "../_components/public-form";

export const metadata: Metadata = { title: "Verified Reviews", description: "Read moderated feedback from real Nexvia users and submit your own verified product review.", alternates: { canonical: "/reviews" } };

export default async function ReviewsPage() {
  const supabase = await createClient();
  const [reviews, authResult] = await Promise.all([getApprovedReviews(), supabase.auth.getUser()]);
  const user = authResult.data.user;
  return <main className="mx-auto w-full max-w-6xl px-5 py-16 sm:px-8"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Verified feedback</p><h1 className="mt-4 font-display text-4xl uppercase text-white sm:text-6xl">Real reviews, never invented testimonials.</h1><p className="mt-5 text-lg leading-8 text-slate-400">Only feedback submitted by signed-in users and approved after moderation appears here.</p></div><section className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{reviews.length ? reviews.map((review) => <article key={review.id} className="rounded-3xl border border-white/10 bg-white/[.03] p-6"><p className="text-amber-300" aria-label={`${review.rating} out of 5 stars`}>{"★".repeat(review.rating)}<span className="text-slate-700">{"★".repeat(5 - review.rating)}</span></p><blockquote className="mt-4 leading-7 text-slate-200">“{review.review}”</blockquote><p className="mt-5 font-semibold text-white">{review.reviewer_name}</p><p className="text-xs text-slate-500">{review.reviewer_role}</p></article>) : <div className="md:col-span-2 lg:col-span-3 rounded-3xl border border-dashed border-white/15 p-10 text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-violet-300">Pilot testing begins soon</p><h2 className="mt-3 text-2xl font-semibold text-white">Be among the first 50 testers</h2><p className="mx-auto mt-3 max-w-2xl text-slate-400">Try the judge demo, then help us validate the student, faculty and recruiter journeys without manufactured proof.</p><div className="mt-6 flex flex-wrap justify-center gap-2">{["Student feedback", "Faculty feedback", "Recruiter feedback"].map((category) => <span key={category} className="rounded-full border border-white/10 bg-white/[.04] px-3 py-1.5 text-xs text-slate-300">{category}</span>)}</div><Link href="/demo" className="mt-7 inline-flex rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-950">Try the judge demo</Link></div>}</section><section className="mt-16 rounded-3xl border border-violet-300/20 bg-violet-400/[.05] p-6 sm:p-8">{user ? <div className="grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-bold text-white">Share your Nexvia experience</h2><p className="mt-3 leading-7 text-slate-400">Your submission is connected to a signed-in account and moderated before publication.</p></div><ReviewForm /></div> : <div className="text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-violet-400/15 text-violet-200">✓</span><h2 className="mt-5 text-3xl font-bold text-white">Sign in to submit a verified review</h2><p className="mx-auto mt-3 max-w-xl leading-7 text-slate-400">The review form unlocks after authentication so visitors can trust that published feedback comes from real accounts.</p><Link href="/login" className="mt-6 inline-flex rounded-xl bg-white px-5 py-3 font-bold text-slate-950">Sign in to review</Link></div>}</section></main>;
}
